import type {
  CoachingProjection,
  MatchDetail,
  MatchPlayerDetail,
  MatchRoundPlayerStat,
  MatchSummary,
} from "../domain/types";

export function sanitizedMatchSummary(overrides: Partial<MatchSummary> = {}): MatchSummary {
  return {
    matchId: "sanitized-match-001",
    mode: "competitive",
    mapName: "Haven",
    gameVersion: "release-13.02-shipping-sanitized",
    patch: "13.02",
    agentName: "Sova",
    seasonId: "sanitized-season",
    seasonShort: "E11A3",
    startedAt: "2026-06-12T10:00:00.000Z",
    durationMs: 2_100_000,
    result: "win",
    roundsWon: 13,
    roundsLost: 8,
    kills: 21,
    deaths: 12,
    assists: 5,
    score: 5_100,
    tierId: 18,
    tierName: "Diamond I",
    placement: 2,
    acs: 244,
    adr: 158,
    damageDelta: 22,
    kast: 0.74,
    headshots: 34,
    bodyshots: 76,
    legshots: 8,
    weapons: ["Vandal"],
    teammates: ["Teammate#EU"],
    opponents: ["Opponent#EU"],
    opponentAgents: ["Omen"],
    teamCompositions: [],
    highlights: ["3K", "Clutch"],
    partySize: 2,
    ...overrides,
  };
}

export function sanitizedMatchDetail(overrides: Partial<MatchDetail> = {}): MatchDetail {
  const focus = player("sanitized-profile-puuid", "SamplePlayer", "Blue", {
    agentName: "Sova",
    kills: 21,
    deaths: 12,
    assists: 5,
    acs: 244,
    adr: 158,
    damageDelta: 22,
    headshotRate: 34 / 118,
    kast: 0.74,
    firstKills: 1,
    firstDeaths: 0,
  });
  const opponent = player("sanitized-opponent-puuid", "Opponent", "Red", {
    agentName: "Omen",
    kills: 12,
    deaths: 21,
    assists: 4,
    acs: 171,
    adr: 122,
    damageDelta: -22,
    headshotRate: 0.2,
    kast: 0.61,
    firstKills: 0,
    firstDeaths: 1,
  });
  const roundPlayer: MatchRoundPlayerStat = {
    puuid: focus.puuid,
    gameName: focus.gameName,
    tagLine: focus.tagLine,
    teamId: focus.teamId,
    score: 310,
    kills: 1,
    headshots: 1,
    bodyshots: 0,
    legshots: 0,
    loadoutValue: 3_900,
    remainingCredits: 600,
    weaponName: "Vandal",
    armorName: "Heavy Shields",
    damageEvents: [],
    abilityCasts: { grenade: 0, ability1: 1, ability2: 0, ultimate: 0, total: 1 },
    wasAfk: false,
    receivedPenalty: false,
    stayedInSpawn: false,
  };
  const coaching: CoachingProjection = {
    modelVersion: "evidence-coaching-v4",
    promptVersion: "deterministic-v4",
    packetHash: "a".repeat(64),
    matchId: "sanitized-match-001",
    focusPuuid: focus.puuid!,
    generatedAt: "2026-06-12T10:30:00.000Z",
    cached: true,
    coverage: {
      rounds: { available: 1, expected: 21 },
      killEvents: { available: 1, positioned: 1 },
      economyRounds: { available: 1, complete: 1 },
      objectives: { available: 0 },
      sources: { available: 1, providers: ["synthetic-provider"], conflictState: "unknown" },
      continuousPov: false,
      comms: false,
      intent: false,
      crosshairPlacement: false,
      continuousMovement: false,
    },
    claims: [
      {
        id: "match-result",
        label: "observed",
        confidence: "high",
        text: "The stored match end state is completed on Haven.",
        evidenceIds: ["match:sanitized-match-001"],
      },
    ],
    strengths: ["The stored result and scoreboard are available."],
    practicePriorities: ["Review the cited opening event."],
    limitations: ["No continuous POV, comms, intent, crosshair placement, or continuous movement is stored."],
  };
  return {
    matchId: "sanitized-match-001",
    region: "eu",
    platform: "pc",
    mode: "Competitive",
    mapName: "Haven",
    gameVersion: "release-13.02-shipping-sanitized",
    patch: "13.02",
    startedAt: "2026-06-12T10:00:00.000Z",
    durationMs: 2_100_000,
    averageTierName: "Diamond I",
    endState: { kind: "completed", label: "Completed", evidence: "team-result" },
    teams: [
      {
        teamId: "Blue",
        label: "Team A",
        roundsWon: 13,
        roundsLost: 8,
        won: true,
        averageTierName: "Diamond I",
        players: [focus],
      },
      {
        teamId: "Red",
        label: "Team B",
        roundsWon: 8,
        roundsLost: 13,
        won: false,
        averageTierName: "Diamond I",
        players: [opponent],
      },
    ],
    rounds: [
      {
        number: 1,
        winningTeam: "Blue",
        result: "Elimination",
        ceremony: null,
        spikePlant: null,
        spikeDefuse: null,
        teamScores: [{ teamId: "Blue", roundsWon: 1 }],
        playerStats: [roundPlayer],
      },
    ],
    killEvents: [
      {
        round: 0,
        timeInRoundMs: 15_000,
        timeInMatchMs: 75_000,
        killerPuuid: focus.puuid,
        killerName: focus.gameName,
        killerTag: focus.tagLine,
        killerTeam: focus.teamId,
        victimPuuid: opponent.puuid,
        victimName: opponent.gameName,
        victimTag: opponent.tagLine,
        victimTeam: opponent.teamId,
        weaponName: "Vandal",
        assistants: [],
        assistantPuuids: [],
        victimLocation: { x: 2_300, y: -7_500 },
        playerLocations: [
          {
            puuid: focus.puuid,
            gameName: focus.gameName,
            tagLine: focus.tagLine,
            teamId: focus.teamId,
            viewRadians: 1.2,
            location: { x: 1_900, y: -7_900 },
          },
        ],
        distanceMeters: 7,
      },
    ],
    economy: {
      modelVersion: "match-economy-v1",
      teams: [
        {
          teamId: "Blue",
          label: "Team A",
          averageBank: 600,
          averageLoadout: 3_900,
          averageTotal: 4_500,
          roundsWithData: 1,
          completeRounds: 1,
          expectedRounds: 1,
          rounds: [
            {
              roundNumber: 1,
              bank: 600,
              loadout: 3_900,
              total: 4_500,
              playerSamples: 1,
              expectedPlayers: 1,
              complete: true,
            },
          ],
        },
      ],
      warnings: [],
    },
    roundEvidence: {
      modelVersion: "match-round-evidence-v1",
      rounds: [
        {
          roundNumber: 1,
          winningTeam: "Blue",
          result: "Elimination",
          players: [
            {
              puuid: focus.puuid,
              gameName: focus.gameName,
              tagLine: focus.tagLine,
              teamId: focus.teamId,
              agentName: focus.agentName,
              score: 310,
              kills: 1,
              deaths: 0,
              assists: 0,
              loadoutValue: 3_900,
              remainingCredits: 600,
              weaponName: "Vandal",
              armorName: "Heavy Shields",
            },
          ],
          events: [
            {
              id: "r1-kill-0",
              kind: "kill",
              timeInRoundMs: 15_000,
              actor: { puuid: focus.puuid, gameName: focus.gameName, tagLine: focus.tagLine, teamId: focus.teamId },
              target: {
                puuid: opponent.puuid,
                gameName: opponent.gameName,
                tagLine: opponent.tagLine,
                teamId: opponent.teamId,
              },
              weaponName: "Vandal",
              assistants: [],
              distanceMeters: 7,
              targetLocation: { x: 2_300, y: -7_500 },
              playerLocations: [
                {
                  puuid: focus.puuid,
                  gameName: focus.gameName,
                  tagLine: focus.tagLine,
                  teamId: focus.teamId,
                  viewRadians: 1.2,
                  location: { x: 1_900, y: -7_900 },
                },
              ],
              site: null,
            },
          ],
        },
      ],
      evidence: { rounds: 1, killEvents: 1, killsWithDistance: 1, killsWithPlayerLocations: 1 },
      warnings: [],
    },
    coaching,
    focusRankChange: null,
    source: "live",
    warnings: [],
    ...overrides,
  };
}

function player(
  puuid: string,
  gameName: string,
  teamId: string,
  overrides: Partial<MatchPlayerDetail>,
): MatchPlayerDetail {
  return {
    puuid,
    gameName,
    tagLine: "EU",
    teamId,
    partyId: null,
    agentName: null,
    level: 200,
    tierId: 18,
    tierName: "Diamond I",
    score: 4_000,
    trackerScore: null,
    kills: null,
    deaths: null,
    assists: null,
    acs: null,
    adr: null,
    damageDelta: null,
    headshotRate: null,
    kast: null,
    firstKills: null,
    firstDeaths: null,
    threePlusKillRounds: null,
    multiKills: null,
    highlights: [],
    spentOverall: null,
    spentAverage: null,
    loadoutOverall: null,
    loadoutAverage: null,
    abilityCasts: { grenade: null, ability1: null, ability2: null, ultimate: null, total: null },
    ...overrides,
  };
}
